server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/nikser871/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:

#          search-locations: "file:///C://Users//nikul//Documents//config"
#          search-locations: "classpath:/config"